### ISSUE TITLE
How about comparing with pooling with kernel size 3x3

### ISSUE THREAD

**Issue by wintersurvival** [richzhang/antialiased-cnns#2]
pooling with kernel size 3x3 is widely used, for example, resnet. pooling of kernel size 3x3 may have stronger low-pass filtering function than 2x2. it would be more convincing if pooling with kernel size 3x3 is compared.

**Comment by richzhang** [comment]
You can try 3x3, 4x4, or any size that may be convincing. Keep in mind that anti-aliasing is an orthogonal design choice, compatible with the max kernel size (Fig 2).

Resnet has one max-pooling (k=3, s=2), but predominantly uses strided-convolutions to downsample.

Closing this because it's not a code-related. Thanks for your patience on the code!
